services:
  - type: web
    name: news-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free

  - type: cron
    name: news-fetcher
    env: python
    schedule: "0 0 */3 * *"  # Every 3 days at midnight UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python fetch_news.py
    plan: free
